/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import Controlador.Metodos;
import Modelo.Producto;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author ronni
 */
public class Heladeria extends javax.swing.JFrame {

    public static Metodos controller;
    DefaultTableModel modelo;
    TableRowSorter<TableModel> ordenar;
    static Producto p;

    public Heladeria() {
        initComponents();
        this.setLocationRelativeTo(null);
        controller = new Metodos();
        menu();
        modelo = (DefaultTableModel) jTable1.getModel();
        ordenar = new TableRowSorter<TableModel>(modelo);
        jTable1.setRowSorter(ordenar);
        BtnBorrar.setEnabled(false);
        LlenarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        PMenu = new javax.swing.JPanel();
        BtnSalir = new javax.swing.JButton();
        BtnRegistrar = new javax.swing.JButton();
        BtnInventario = new javax.swing.JButton();
        BtnVentas = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        PInventario = new javax.swing.JPanel();
        BtnV2 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        AreaB = new javax.swing.JTextArea();
        BtnBorrar = new javax.swing.JButton();
        TxtB = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        BtnBuscar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        PRegistrar = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        BtnV1 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        Txt1 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        Txt2 = new javax.swing.JTextField();
        Txt3 = new javax.swing.JTextField();
        BtnAgregar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        PVentas = new javax.swing.JPanel();
        BtnV3 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        Box2 = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        AreaT = new javax.swing.JTextArea();
        BtnComprar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        jLabel6.setText("jLabel6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(730, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PMenu.setPreferredSize(new java.awt.Dimension(730, 500));
        PMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ICONOSALIR.png"))); // NOI18N
        BtnSalir.setBorder(null);
        BtnSalir.setBorderPainted(false);
        BtnSalir.setContentAreaFilled(false);
        BtnSalir.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ICONOSALIR.png"))); // NOI18N
        BtnSalir.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ICONOSALIR2_2.png"))); // NOI18N
        BtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSalirActionPerformed(evt);
            }
        });
        PMenu.add(BtnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 0, 50, 50));

        BtnRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/registrar.png"))); // NOI18N
        BtnRegistrar.setBorder(null);
        BtnRegistrar.setBorderPainted(false);
        BtnRegistrar.setContentAreaFilled(false);
        BtnRegistrar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/registrar.png"))); // NOI18N
        BtnRegistrar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/registrar2.png"))); // NOI18N
        BtnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRegistrarActionPerformed(evt);
            }
        });
        PMenu.add(BtnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 280, -1, -1));

        BtnInventario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/inventario.png"))); // NOI18N
        BtnInventario.setBorder(null);
        BtnInventario.setBorderPainted(false);
        BtnInventario.setContentAreaFilled(false);
        BtnInventario.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/inventario.png"))); // NOI18N
        BtnInventario.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/inventario2.png"))); // NOI18N
        BtnInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnInventarioActionPerformed(evt);
            }
        });
        PMenu.add(BtnInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 380, -1, -1));

        BtnVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/venta.png"))); // NOI18N
        BtnVentas.setBorder(null);
        BtnVentas.setBorderPainted(false);
        BtnVentas.setContentAreaFilled(false);
        BtnVentas.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/venta.png"))); // NOI18N
        BtnVentas.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/venta2.png"))); // NOI18N
        BtnVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVentasActionPerformed(evt);
            }
        });
        PMenu.add(BtnVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 300, 110, 110));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo .png"))); // NOI18N
        PMenu.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(PMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 700));

        PInventario.setMinimumSize(new java.awt.Dimension(730, 500));
        PInventario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnV2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/volver.png"))); // NOI18N
        BtnV2.setBorder(null);
        BtnV2.setBorderPainted(false);
        BtnV2.setContentAreaFilled(false);
        BtnV2.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/volver.png"))); // NOI18N
        BtnV2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/volver2.png"))); // NOI18N
        BtnV2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnV2ActionPerformed(evt);
            }
        });
        PInventario.add(BtnV2, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 0, -1, -1));

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Producto", "Precio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(84, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Consultar", jPanel1);

        jPanel3.setBackground(new java.awt.Color(255, 153, 153));

        AreaB.setColumns(20);
        AreaB.setRows(5);
        jScrollPane2.setViewportView(AreaB);

        BtnBorrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ICONOBAJAS.png"))); // NOI18N
        BtnBorrar.setBorder(null);
        BtnBorrar.setBorderPainted(false);
        BtnBorrar.setContentAreaFilled(false);
        BtnBorrar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ICONOBAJAS.png"))); // NOI18N
        BtnBorrar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ICONOBAJAS2.png"))); // NOI18N
        BtnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBorrarActionPerformed(evt);
            }
        });

        TxtB.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        TxtB.setPreferredSize(new java.awt.Dimension(131, 37));
        TxtB.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtBKeyTyped(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel18.setText("ID:");

        BtnBuscar.setBackground(new java.awt.Color(0, 0, 204));
        BtnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        BtnBuscar.setText("Buscar");
        BtnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addGap(18, 18, 18)
                        .addComponent(TxtB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(BtnBuscar))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(46, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnBorrar)
                .addGap(291, 291, 291))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(BtnBuscar))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnBorrar)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Eliminar", jPanel3);

        PInventario.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 650, 420));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo2.png"))); // NOI18N
        PInventario.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(PInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 500));

        PRegistrar.setPreferredSize(new java.awt.Dimension(730, 500));
        PRegistrar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Forte", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 0, 153));
        jLabel2.setText("Registro");
        PRegistrar.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, -1, -1));

        BtnV1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/volver.png"))); // NOI18N
        BtnV1.setBorder(null);
        BtnV1.setBorderPainted(false);
        BtnV1.setContentAreaFilled(false);
        BtnV1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/volver.png"))); // NOI18N
        BtnV1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/volver2.png"))); // NOI18N
        BtnV1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnV1ActionPerformed(evt);
            }
        });
        PRegistrar.add(BtnV1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 0, -1, -1));

        jLabel12.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(153, 0, 153));
        jLabel12.setText("ID:");
        PRegistrar.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, -1, -1));

        Txt1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        Txt1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Txt1KeyTyped(evt);
            }
        });
        PRegistrar.add(Txt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 160, -1));

        jLabel13.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(153, 0, 153));
        jLabel13.setText("Producto:");
        PRegistrar.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, -1, -1));

        jLabel14.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(153, 0, 153));
        jLabel14.setText("Precio:");
        PRegistrar.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 190, -1, -1));

        Txt2.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        Txt2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Txt2KeyTyped(evt);
            }
        });
        PRegistrar.add(Txt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 290, 160, -1));

        Txt3.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        Txt3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Txt3KeyTyped(evt);
            }
        });
        PRegistrar.add(Txt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 190, 160, -1));

        BtnAgregar.setBackground(new java.awt.Color(204, 0, 204));
        BtnAgregar.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        BtnAgregar.setForeground(new java.awt.Color(255, 255, 255));
        BtnAgregar.setText("Agregar");
        BtnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAgregarActionPerformed(evt);
            }
        });
        PRegistrar.add(BtnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 400, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo1.png"))); // NOI18N
        PRegistrar.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(PRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 500));

        PVentas.setPreferredSize(new java.awt.Dimension(730, 500));
        PVentas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnV3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/volver.png"))); // NOI18N
        BtnV3.setBorder(null);
        BtnV3.setBorderPainted(false);
        BtnV3.setContentAreaFilled(false);
        BtnV3.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/volver.png"))); // NOI18N
        BtnV3.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/volver2.png"))); // NOI18N
        BtnV3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnV3ActionPerformed(evt);
            }
        });
        PVentas.add(BtnV3, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 0, -1, -1));

        jLabel16.setFont(new java.awt.Font("Forte", 1, 48)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(153, 51, 255));
        jLabel16.setText("Ventanilla");
        PVentas.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, -1, -1));

        Box2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        Box2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "..." }));
        PVentas.add(Box2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 190, -1));

        jLabel17.setFont(new java.awt.Font("Cooper Black", 1, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(102, 51, 0));
        jLabel17.setText("Elige un producto:");
        PVentas.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        AreaT.setColumns(20);
        AreaT.setRows(5);
        jScrollPane3.setViewportView(AreaT);

        PVentas.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 160, 320, 300));

        BtnComprar.setBackground(new java.awt.Color(0, 204, 51));
        BtnComprar.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        BtnComprar.setForeground(new java.awt.Color(255, 255, 0));
        BtnComprar.setText("Comprar");
        BtnComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnComprarActionPerformed(evt);
            }
        });
        PVentas.add(BtnComprar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo3.png"))); // NOI18N
        PVentas.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(PVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRegistrarActionPerformed
        PMenu.setVisible(false);
        PRegistrar.setVisible(true);
    }//GEN-LAST:event_BtnRegistrarActionPerformed

    private void BtnInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnInventarioActionPerformed
        PMenu.setVisible(false);
        PInventario.setVisible(true);
    }//GEN-LAST:event_BtnInventarioActionPerformed

    private void BtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_BtnSalirActionPerformed

    private void BtnV1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnV1ActionPerformed
        menu();
    }//GEN-LAST:event_BtnV1ActionPerformed

    private void BtnV2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnV2ActionPerformed
        menu();
    }//GEN-LAST:event_BtnV2ActionPerformed

    private void BtnV3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnV3ActionPerformed
        menu();
    }//GEN-LAST:event_BtnV3ActionPerformed

    private void BtnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAgregarActionPerformed
        String id = Txt1.getText();
        String nombre = Txt2.getText();
        String precio = Txt3.getText();
        if ((id.isEmpty() || nombre.isEmpty() || precio.isEmpty())) {
            JOptionPane.showMessageDialog(this, "Debe rellenar todo", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            modelo.setRowCount(0);
            LlenarLista();
            LlenarTabla();
        }
    }//GEN-LAST:event_BtnAgregarActionPerformed

    private void Txt1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Txt1KeyTyped
        char car = evt.getKeyChar();
        int limite = 7;
        if (Character.isDigit(car) && Txt1.getText().length() != limite) {

        } else {
            evt.consume();
        }
    }//GEN-LAST:event_Txt1KeyTyped

    private void Txt2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Txt2KeyTyped
//        char car = evt.getKeyChar();
//        //int limite = 20;
//        if (Character.isLetter(car)) {
//            
//        } else {
//            evt.consume();
//        }
    }//GEN-LAST:event_Txt2KeyTyped

    private void Txt3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Txt3KeyTyped
        char car = evt.getKeyChar();
        int limite = 4;
        String n = Txt3.getText();
        if (Character.isDigit(car) && Txt3.getText().length() != limite) {

        } else {
            evt.consume();
        }
    }//GEN-LAST:event_Txt3KeyTyped

    private void TxtBKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtBKeyTyped
        char car = evt.getKeyChar();
        int limite = 7;
        if (Character.isDigit(car) && TxtB.getText().length() != limite) {

        } else {
            evt.consume();
        }
    }//GEN-LAST:event_TxtBKeyTyped

    private void BtnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBuscarActionPerformed
        String n = TxtB.getText();
        if (n.equals("")) {
            JOptionPane.showMessageDialog(this, "Debe de agregar un id", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            String info = "";
            try {
                int num = Integer.parseInt(n);
                controller.insercionDirecta();
                p = controller.busquedaBinariaID(num, 0, controller.lista.size() - 1);
                info = p.toString();
                AreaB.setText(info);
                BtnBorrar.setEnabled(true);
            } catch (NullPointerException | NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "ID no existente", "Error", JOptionPane.ERROR_MESSAGE);
            }

//            if (controller.buscar(n)) {
//                String datos = controller.MostrarporID(n);
//                BtnBorrar.setEnabled(true);
//                AreaB.setText(datos);
//            } else {
//                JOptionPane.showMessageDialog(this, "ID no existente", "Error", JOptionPane.ERROR_MESSAGE);
//            }
        }
    }//GEN-LAST:event_BtnBuscarActionPerformed

    private void BtnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBorrarActionPerformed
        BtnBorrar.setEnabled(false);
        int c = 0;
        String n = TxtB.getText();
        if (n.equals("")) {
            JOptionPane.showMessageDialog(this, "Talvez quito el ID", "Error", JOptionPane.WARNING_MESSAGE);
            AreaB.setText("");
        } else {
            int r = JOptionPane.showConfirmDialog(null, "¿Seguro que lo quiere borrar?");
            if (r == JOptionPane.YES_OPTION) {
                 int num = Integer.parseInt(n);
                 for (Producto p : controller.lista) {                    
                    if (num == p.getID()) {                                             
                        break;
                    }
                    c++;
                }
                controller.insercionDirecta();
                p = controller.busquedaBinariaID(num, 0, controller.lista.size() - 1);
               if(p!=null){
                   String m = p.getNombre();
                   Box2.removeItem(m);
                        AreaB.setText("");
                        TxtB.setText("");
                        JOptionPane.showMessageDialog(null, "El producto fue eliminado");                       
               }
                
                modelo.removeRow(c);
            } else {
                if (r == JOptionPane.NO_OPTION) {
                    AreaB.setText("");
                    TxtB.setText("");
                    JOptionPane.showMessageDialog(null, "Bueno, sera en otro momento");
                }
            }
        }
    }//GEN-LAST:event_BtnBorrarActionPerformed

    private void BtnVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVentasActionPerformed
        PMenu.setVisible(false);
        PVentas.setVisible(true);
    }//GEN-LAST:event_BtnVentasActionPerformed

    private void BtnComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnComprarActionPerformed
        int pr = 0;
        if (Box2.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "Debe elegir un producto", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            String n = (String) Box2.getSelectedItem();
            controller.insercionDirecta();
            Producto p = controller.busquedaBinariaNom(n, 0, controller.lista.size() - 1);
            if(p!=null){
                pr = p.getPrecio();
            }
//            for (Producto p : controller.lista) {
//                if (n.equals(p.getNombre())) {
//                    pr = p.getPrecio();
//                }
//                
//            }
            
            AreaT.append("************************RECIBO************************" + "\n");
            AreaT.append("HELADERIA: FROST" + "\n");
            AreaT.append("Producto: " + n + "\n");
            AreaT.append("Costo: " + pr + " pesos" + "\n");
            AreaT.append("\n");
            AreaT.append("\n");
            AreaT.append("\n");
            AreaT.append("Vuelva pronto ;)" + "\n");
        }
    }//GEN-LAST:event_BtnComprarActionPerformed

    public void LlenarLista() {
        String id = Txt1.getText();
        int i = Integer.parseInt(id);
        if (!controller.buscar2(id)) {
            String nombre = Txt2.getText();
            String precio = Txt3.getText();
            int p = Integer.parseInt(precio);
            controller.Agregar(i, nombre, p);
            Box2.addItem(nombre);
            JOptionPane.showMessageDialog(null, "Producto registrado");
            Txt1.setText("");
            Txt2.setText("");
            Txt3.setText("");
        } else {
            JOptionPane.showMessageDialog(this, "ID ya existente", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    public void LlenarTabla() {
        for (int x = 0; x < controller.lista.size(); x++) {
            Object[] datos = new Object[modelo.getColumnCount()];
            datos[0] = controller.lista.get(x).getID();
            datos[1] = controller.lista.get(x).getNombre();
            datos[2] = controller.lista.get(x).getPrecio();
            modelo.addRow(datos);
        }
    }

//    public void borrarFilasCon(String n) {
//        for (int f = 0; f < modelo.getRowCount(); f++) {
//            for (int c = 0; c < modelo.getColumnCount(); c++) {
//                if (modelo.getValueAt(f, c).equals(n)) {
//                    modelo.removeRow(f);
//
//                }
//            }
//        }
//    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Heladeria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Heladeria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Heladeria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Heladeria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Heladeria().setVisible(true);
            }
        });
    }

    private void menu() {
        PMenu.setVisible(true);
        PRegistrar.setVisible(false);
        PInventario.setVisible(false);
        PVentas.setVisible(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea AreaB;
    private javax.swing.JTextArea AreaT;
    private javax.swing.JComboBox<String> Box2;
    private javax.swing.JButton BtnAgregar;
    private javax.swing.JButton BtnBorrar;
    private javax.swing.JButton BtnBuscar;
    private javax.swing.JButton BtnComprar;
    private javax.swing.JButton BtnInventario;
    private javax.swing.JButton BtnRegistrar;
    private javax.swing.JButton BtnSalir;
    private javax.swing.JButton BtnV1;
    private javax.swing.JButton BtnV2;
    private javax.swing.JButton BtnV3;
    private javax.swing.JButton BtnVentas;
    private javax.swing.JPanel PInventario;
    private javax.swing.JPanel PMenu;
    private javax.swing.JPanel PRegistrar;
    private javax.swing.JPanel PVentas;
    private javax.swing.JTextField Txt1;
    private javax.swing.JTextField Txt2;
    private javax.swing.JTextField Txt3;
    private javax.swing.JTextField TxtB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
